# Generated by Django 3.1 on 2020-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='this is a bio', max_length=80),
            preserve_default=False,
        ),
    ]
