# Generated by Django 3.1 on 2020-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_author_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author_date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_required',
            field=models.CharField(default='half hour', max_length=50),
            preserve_default=False,
        ),
    ]
